[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "else_bot"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "else bot common core"
readme = "README.md"
requires-python = ">=3.8"